apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: supanart2010/gateway-service:v2.0
        ports:
        - containerPort: 8001
        env:
        - name: REST_URL
          value: http://dataset-mgmt-service:8000
        - name: GRPC_URL
          value: http://data-entry-getter-service:8002
        - name: RABBITMQ_URL
          value: rabbitmq-amqp-service
        - name: DATABASE_URL
          value: mongodb://mongodb-service:27017/
        - name: OAUTH_SECRET_KEY
          value: 40685ce01419b8e886136d45c37fb061b02a1060e3b5cbec83512234fe617ae3
        - name: OAUTH_ALGORITHM
          value: HS256
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001