apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 2
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: supanart2010/new-todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: todo-db-service
            - name: NOTIFICATION_HOST
              value: todo-noti-service
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000