apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-noti-deployment
  labels:
    app: todo-noti
spec:
  selector:
    matchLabels:
      app: todo-noti
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-noti
    spec:
      containers:
        - name: todo-noti
          image: natawut/todo-notification:release-1.1
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_HOST
              value: todo-db-service
          
---
apiVersion: v1
kind: Service
metadata:
  name: todo-noti-service
spec:
  selector:
    app: todo-noti
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000