apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
      containers:
        - name: todo
          image: natawut/todo-service:release-2.1
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: todo-db-service
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000